title: nico.ninja
tagline: A deep dive journey about electronics, computers, radio and so on
description: Electronics, computers, radio, IoT, motorsports, software development and microcontroller-based projects
baseurl: ""
url: "https://blog.nico.ninja"
author: Nicolas Rey
github_username: reynico
twitter_username: reynico
permalink: /:categories/:title/
highlighter: none

plugins:
  - jekyll-feed
  - jekyll-sitemap

feed:
  path: feed.xml

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - hooks/
  - compose.yml
  - Gemfile
  - Gemfile.lock
  - vendor/
