title: nico.ninja
tagline: A deep dive journey about electronics, computers, radio and so on
description: Electronics, computers, radio, IoT, motorsports, software development and microcontroller-based projects
baseurl: ""
url: "https://blog.nico.ninja"
twitter_username: reynico
github_username:  reynico
permalink: /:categories/:title/
paginate: 5
disqus:
  shortname: blog-nico-ninja

# Build settings
remote_theme: poole/lanyon

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

