title: nico.ninja
description: >-
  Electronics, computers, radio and so on
baseurl: ""
url: "https://blog.nico.ninja"
twitter_username: reynico
github_username:  reynico
permalink: /:categories/:title/

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

